name: FPG 自動化流程

on:
  # schedule:
  #   - cron: '0 0 * * 1-5' # 每個工作日 UTC 00:00 / 台灣時間 08:00 運行
  workflow_dispatch: # 允許手動觸發工作流程，暫時只保留手動觸發功能

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v3

      - name: 設置 Node.js 環境
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'

      - name: 安裝依賴套件
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install

      - name: 安裝系統依賴
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable xvfb

      - name: 執行自動化腳本
        env:
          AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
          AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
          LOGIN_URL: ${{ secrets.LOGIN_URL }}
          FPG_USERNAME: ${{ secrets.FPG_USERNAME }}
          FPG_PASSWORD: ${{ secrets.FPG_PASSWORD }}
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
          CHROME_PATH: '/usr/bin/google-chrome-stable'
          HEADLESS: 'true'
        run: |
          xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" node fpgAutomation.js || {
            echo "腳本執行失敗，錯誤代碼: $?"
            echo "錯誤日誌:"
            cat error.log
            exit 1
          }

      - name: 上傳日誌和截圖
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: automation-artifacts
          path: |
            logs/
            screenshots/
            error.log
          if-no-files-found: warn
