name: FPG 自動化流程

on:
  schedule:
    - cron: '0 0 * * 1-5'  # UTC 時間 00:00，相當於台灣時間 08:00
  workflow_dispatch:  # 允許手動觸發工作流程

jobs:
  run-automation:
    runs-on: ubuntu-latest
    steps:
    - name: 檢出程式碼
      uses: actions/checkout@v3

    - name: 設置 Node.js 環境
      uses: actions/setup-node@v3
      with:
        node-version: '18.17.0'

    - name: 安裝相依套件
      run: npm ci

    - name: 執行自動化腳本
      env:
        AZURE_ENDPOINT: ${{ secrets.AZURE_ENDPOINT }}
        AZURE_API_KEY: ${{ secrets.AZURE_API_KEY }}
        LOGIN_URL: ${{ secrets.LOGIN_URL }}
        FPG_USERNAME: ${{ secrets.FPG_USERNAME }}
        FPG_PASSWORD: ${{ secrets.FPG_PASSWORD }}
      run: node fpgAutomation.js

    - name: 上傳日誌檔案（如果有的話）
      uses: actions/upload-artifact@v3  # 更新到 v3 版本
      if: always()
      with:
        name: execution-logs
        path: logs/
        if-no-files-found: ignore
